server:
  port: 8081
spring:
  #autoconfigure:
  #  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    #url: jdbc:oracle:thin:@localhost:1521:ORCLPDB1
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    driver-class-name: oracle.jdbc.OracleDriver
    username: JPA_RELATIONS
    password: relations
    jpa:
      show-sql: true
      format-sql: true
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
      database-platform: org.hibernate.dialect.Oracle12cDialect
  sql:
    init:
      continue-on-error: true